#!/usr/bin/bash

DIR=$(dirname "$0")

if [[ -f CMakeLists.txt ]]; then
    echo "modifying existing CMakeLists.txt"
else
    cp "$DIR/olymp/CMakeLists.txt" .
fi
cp "$DIR/olymp/Olymp.cpp" main.cpp
for i in $@; do
  if [[ $i == vscode ]]; then
    cp -r "$DIR/olymp/.vscode" .
    code .
  elif [[ $i == gvim ]]; then
    gvim .
  else
    cp "$DIR/olymp/Olymp.cpp" $i.cpp
    echo "add_executable($i $i.cpp)" >> CMakeLists.txt
    echo "target_precompile_headers($i REUSE_FROM main)" >> CMakeLists.txt
  fi
done
